# Generated by Django 4.2.7 on 2023-12-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyMusic',
        ),
    ]
