# Generated by Django 4.2.7 on 2023-12-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('myaudio', '0003_alter_mymusic_music_alter_mymusic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_music', to='main.music'),
        ),
    ]
