# Generated by Django 4.2.7 on 2023-12-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='release',
        ),
        migrations.AlterField(
            model_name='music',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True, verbose_name='слаг'),
        ),
    ]
